import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/app/QueryProvider";
import { Header } from "@/app/(main)/Header";
import Footer from "./(main)/Footer";
import { ThemeProvider } from 'next-themes'



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <QueryProvider>
            <div className="relative text-light-text dark:text-dark-text bg-light-background dark:bg-dark-background min-h-screen">
              <Header />
              <main>{children}</main>
              <Footer />
            </div>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
