import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/app/QueryProvider";
import { Header } from "@/app/(main)/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <div className="relative text-zinc-800 dark:text-zinc-200">
            <Header />
            <main>{children}</main>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
